name: Task
description: 일반 작업 (리팩토링, 문서화 등)
title: "[Task] "
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        ## 작업 요청
        수행할 작업에 대해 설명해주세요.

  - type: textarea
    id: description
    attributes:
      label: 작업 설명
      description: 어떤 작업이 필요한지 설명해주세요.
      placeholder: UserService 리팩토링이 필요합니다.
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: 작업 유형
      description: 작업 유형을 선택해주세요.
      options:
        - "Refactor - 리팩토링"
        - "Docs - 문서화"
        - "Test - 테스트"
        - "Chore - 설정/빌드"
        - "Style - 코드 스타일"
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: 세부 작업
      description: 세부 작업 목록을 작성해주세요.
      placeholder: |
        - [ ] UserService에서 UserQueryService 분리
        - [ ] 테스트 코드 수정
        - [ ] 관련 문서 업데이트
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 추가 정보
      description: 참고할 만한 추가 정보가 있다면 작성해주세요.
    validations:
      required: false
